name: Deploy to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' 

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build

      - name: Push dist folder to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd dist
          git init
          git checkout -b main
          git add .
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -m "Automated deployment to Hugging Face"
          git remote add origin https://zemen:${HF_TOKEN}@huggingface.co/spaces/zemen/Portfolio
          git push -f origin main
